-- OASIS CRM v10.2.9 - one stored document per business/workplace scope.
-- Raw business and management numbers stay in the encrypted worker payload.
-- collection_key is an opaque discriminator generated by the application.

begin;

alter table public.oasis_claim_documents
    add column if not exists collection_key text not null default 'default';

update public.oasis_claim_documents
set facts = coalesce(facts, '{}'::jsonb) - array[
    'identity_number',
    'birth_date',
    'cellphone',
    'business_number',
    'business_numbers',
    'management_number',
    'management_numbers',
    'resident_number'
]
where coalesce(facts, '{}'::jsonb) ?| array[
    'identity_number',
    'birth_date',
    'cellphone',
    'business_number',
    'business_numbers',
    'management_number',
    'management_numbers',
    'resident_number'
];

do $$
begin
    if not exists (
        select 1
        from pg_constraint
        where conname = 'oasis_claim_documents_collection_key_check'
          and conrelid = 'public.oasis_claim_documents'::regclass
    ) then
        alter table public.oasis_claim_documents
            add constraint oasis_claim_documents_collection_key_check
            check (
                collection_key = 'default'
                or collection_key ~ '^v_[0-9a-f]{32}$'
            );
    end if;
end;
$$;

do $$
declare
    v_constraint_name text;
begin
    for v_constraint_name in
        select c.conname
        from pg_constraint c
        where c.conrelid = 'public.oasis_claim_documents'::regclass
          and c.contype = 'u'
          and (
              select array_agg(a.attname order by keys.ordinality)
              from unnest(c.conkey)
                  with ordinality as keys(attnum, ordinality)
              join pg_attribute a
                on a.attrelid = c.conrelid
               and a.attnum = keys.attnum
          ) = array[
              'owner_user_id',
              'case_id',
              'source',
              'document_code',
              'period_year'
          ]::name[]
    loop
        execute format(
            'alter table public.oasis_claim_documents drop constraint %I',
            v_constraint_name
        );
    end loop;
end;
$$;

do $$
begin
    if not exists (
        select 1
        from pg_constraint
        where conname = 'oasis_claim_documents_variant_unique'
          and conrelid = 'public.oasis_claim_documents'::regclass
    ) then
        alter table public.oasis_claim_documents
            add constraint oasis_claim_documents_variant_unique
            unique nulls not distinct (
                owner_user_id,
                case_id,
                source,
                document_code,
                period_year,
                collection_key
            );
    end if;
end;
$$;

create index if not exists oasis_claim_documents_case_variant_idx
    on public.oasis_claim_documents (
        owner_user_id,
        case_id,
        document_code,
        period_year,
        collection_key
    );

-- The pre-v10.2.9 creator populated a whole composite record. A missing JSON
-- field therefore became an explicit NULL rather than invoking the column
-- default. Normalize legacy payloads before populating the new row type so a
-- rolling deployment cannot break case creation.
create or replace function public.oasis_create_claim_case(
    p_case jsonb,
    p_documents jsonb,
    p_audit jsonb
)
returns uuid
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
    v_case_id uuid := nullif(p_case ->> 'id', '')::uuid;
    v_owner_user_id text := lower(trim(p_case ->> 'owner_user_id'));
    v_documents jsonb;
begin
    if v_case_id is null or coalesce(v_owner_user_id, '') = '' then
        raise exception 'invalid claim case identity';
    end if;
    if jsonb_typeof(coalesce(p_documents, '[]'::jsonb)) <> 'array' then
        raise exception 'claim documents must be an array';
    end if;

    select coalesce(
        jsonb_agg(
            item || jsonb_build_object(
                'collection_key',
                coalesce(
                    nullif(lower(trim(item ->> 'collection_key')), ''),
                    'default'
                )
            )
            order by ordinality
        ),
        '[]'::jsonb
    )
    into v_documents
    from jsonb_array_elements(coalesce(p_documents, '[]'::jsonb))
        with ordinality as document_rows(item, ordinality);

    if exists (
        select 1
        from jsonb_array_elements(v_documents) item
        where nullif(item ->> 'case_id', '')::uuid is distinct from v_case_id
           or lower(trim(item ->> 'owner_user_id'))
                is distinct from v_owner_user_id
    ) then
        raise exception 'claim document ownership mismatch';
    end if;

    insert into public.oasis_claim_cases
    select *
    from jsonb_populate_record(
        null::public.oasis_claim_cases,
        p_case
    );

    if jsonb_array_length(v_documents) > 0 then
        insert into public.oasis_claim_documents
        select *
        from jsonb_populate_recordset(
            null::public.oasis_claim_documents,
            v_documents
        );
    end if;

    insert into public.oasis_claim_audit_events (
        owner_user_id,
        case_id,
        action,
        source,
        outcome,
        metadata
    )
    values (
        v_owner_user_id,
        v_case_id,
        coalesce(nullif(p_audit ->> 'action', ''), 'case_created'),
        coalesce(nullif(p_audit ->> 'source', ''), 'system'),
        coalesce(nullif(p_audit ->> 'outcome', ''), 'success'),
        coalesce(p_audit -> 'metadata', '{}'::jsonb)
    );

    return v_case_id;
end;
$$;

revoke all on function public.oasis_create_claim_case(
    jsonb,
    jsonb,
    jsonb
)
from public, anon, authenticated, service_role;

grant execute on function public.oasis_create_claim_case(
    jsonb,
    jsonb,
    jsonb
)
to service_role;

drop function if exists public.oasis_claim_list_documents(
    text,
    uuid
);

create or replace function public.oasis_claim_list_documents(
    p_owner_user_id text,
    p_case_id uuid,
    p_limit integer default 500,
    p_offset integer default 0
)
returns setof public.oasis_claim_documents
language sql
stable
security definer
set search_path = public, pg_temp
as $$
    select d.*
    from public.oasis_claim_documents d
    where d.owner_user_id = lower(trim(p_owner_user_id))
      and d.case_id = p_case_id
    order by
        d.source asc,
        d.document_code asc,
        d.period_year desc nulls last,
        d.collection_key asc,
        d.id asc
    limit greatest(1, least(coalesce(p_limit, 500), 500))
    offset greatest(0, coalesce(p_offset, 0));
$$;

revoke all on function public.oasis_claim_list_documents(
    text,
    uuid,
    integer,
    integer
)
from public, anon, authenticated, service_role;

grant execute on function public.oasis_claim_list_documents(
    text,
    uuid,
    integer,
    integer
)
to service_role;

create or replace function public.oasis_claim_ensure_document_variant(
    p_owner_user_id text,
    p_case_id uuid,
    p_document_code text,
    p_period_year integer,
    p_collection_key text,
    p_document_id uuid,
    p_facts jsonb default '{}'::jsonb
)
returns setof public.oasis_claim_documents
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
    v_owner_user_id text := lower(trim(p_owner_user_id));
    v_document_code text := trim(p_document_code);
    v_collection_key text := lower(trim(p_collection_key));
    v_facts jsonb := coalesce(p_facts, '{}'::jsonb);
    v_base public.oasis_claim_documents;
    v_document public.oasis_claim_documents;
begin
    if coalesce(v_owner_user_id, '') = ''
       or coalesce(v_document_code, '') = ''
       or coalesce(v_collection_key, '') = ''
       or p_case_id is null
       or p_document_id is null
       or (
           v_collection_key <> 'default'
           and v_collection_key !~ '^v_[0-9a-f]{32}$'
       )
    then
        raise exception 'invalid claim document variant identity';
    end if;
    if jsonb_typeof(v_facts) <> 'object' then
        raise exception 'claim document variant facts must be an object';
    end if;

    v_facts := v_facts - array[
        'identity_number',
        'birth_date',
        'cellphone',
        'business_number',
        'business_numbers',
        'management_number',
        'management_numbers',
        'resident_number'
    ];

    -- document_code/period_year identifies one base plan row in the existing
    -- catalog. Its source is copied below, so callers cannot move a variant
    -- between Hometax and COMWEL.
    select d.*
    into v_base
    from public.oasis_claim_documents d
    where d.owner_user_id = v_owner_user_id
      and d.case_id = p_case_id
      and d.document_code = v_document_code
      and d.period_year is not distinct from p_period_year
      and d.collection_key = 'default'
    limit 1;

    if not found then
        raise exception 'base claim document not found';
    end if;

    if v_collection_key = 'default' then
        update public.oasis_claim_documents d
        set
            facts = coalesce(d.facts, '{}'::jsonb) || v_facts,
            updated_at = now()
        where d.id = v_base.id
          and d.owner_user_id = v_owner_user_id
          and d.case_id = p_case_id
        returning d.* into v_document;
        return next v_document;
        return;
    end if;

    insert into public.oasis_claim_documents (
        id,
        owner_user_id,
        case_id,
        source,
        document_code,
        document_name,
        period_year,
        collection_key,
        status,
        facts,
        created_at,
        updated_at
    )
    values (
        p_document_id,
        v_base.owner_user_id,
        v_base.case_id,
        v_base.source,
        v_base.document_code,
        v_base.document_name,
        v_base.period_year,
        v_collection_key,
        'auth_pending',
        v_facts,
        now(),
        now()
    )
    on conflict on constraint oasis_claim_documents_variant_unique
    do update set
        facts = coalesce(oasis_claim_documents.facts, '{}'::jsonb)
            || excluded.facts,
        updated_at = now()
    returning * into v_document;

    return next v_document;
end;
$$;

revoke all on function public.oasis_claim_ensure_document_variant(
    text,
    uuid,
    text,
    integer,
    text,
    uuid,
    jsonb
)
from public, anon, authenticated, service_role;

grant execute on function public.oasis_claim_ensure_document_variant(
    text,
    uuid,
    text,
    integer,
    text,
    uuid,
    jsonb
)
to service_role;

commit;
