create extension if not exists pgcrypto;

create table if not exists public.oasis_licensed_businesses (
    id uuid primary key default gen_random_uuid(),
    source_key text not null unique,
    service_key text not null,
    category text not null default '',
    industry_name text not null default '',
    management_no text not null default '',
    company_name text not null,
    address text not null default '',
    phone text not null default '',
    business_status_code text not null default '',
    business_status_name text not null default '',
    is_active boolean not null default true,
    license_date text not null default '',
    close_date text not null default '',
    source_data jsonb not null default '{}'::jsonb,
    last_seen_at timestamptz not null default now(),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index if not exists oasis_licensed_businesses_company_idx
    on public.oasis_licensed_businesses (company_name);
create index if not exists oasis_licensed_businesses_category_idx
    on public.oasis_licensed_businesses (category, industry_name);
create index if not exists oasis_licensed_businesses_active_idx
    on public.oasis_licensed_businesses (is_active, service_key);

create table if not exists public.oasis_license_sync_runs (
    id bigint generated by default as identity primary key,
    service_key text not null,
    page_no integer not null default 1,
    received_count integer not null default 0,
    saved_count integer not null default 0,
    status text not null,
    message text not null default '',
    created_at timestamptz not null default now()
);

alter table public.oasis_licensed_businesses enable row level security;
alter table public.oasis_license_sync_runs enable row level security;

revoke all on public.oasis_licensed_businesses from anon, authenticated;
revoke all on public.oasis_license_sync_runs from anon, authenticated;
grant all on public.oasis_licensed_businesses to service_role;
grant all on public.oasis_license_sync_runs to service_role;
