-- OASIS CRM v9.8.4
-- DB발굴 사용자별 검색 이력 및 저장 후보 메모
-- 기존 테이블과 데이터는 삭제하거나 변경하지 않습니다.

alter table public.oasis_prospect_companies
    add column if not exists memo text not null default '';

create table if not exists public.oasis_prospect_search_history (
    id bigint generated by default as identity primary key,
    owner_user_id text not null,
    region text not null default '',
    region_code text not null default '',
    business_type text not null default 'stock',
    start_page integer not null check (start_page >= 1),
    end_page integer not null check (end_page >= start_page),
    target_count integer not null default 30 check (target_count >= 1),
    minimum_employees integer not null default 3
        check (minimum_employees >= 1),
    growth_only boolean not null default true,
    growth_basis text not null default 'year_over_year',
    industry_categories text[] not null default '{}',
    found_count integer not null default 0 check (found_count >= 0),
    pages_scanned integer not null default 0 check (pages_scanned >= 0),
    elapsed_seconds numeric(12, 1) not null default 0
        check (elapsed_seconds >= 0),
    searched_at timestamptz not null default now()
);

alter table public.oasis_prospect_search_history
    add column if not exists growth_basis text
    not null default 'year_over_year';

create index if not exists
    idx_oasis_prospect_search_history_owner_time
on public.oasis_prospect_search_history (
    owner_user_id,
    searched_at desc
);

create index if not exists
    idx_oasis_prospect_search_history_owner_range
on public.oasis_prospect_search_history (
    owner_user_id,
    region_code,
    business_type,
    start_page,
    end_page
);

comment on column public.oasis_prospect_companies.memo is
    '저장된 영업후보의 공용 업무 메모';

comment on table public.oasis_prospect_search_history is
    'DB발굴에서 사용자별로 완료한 국민연금 페이지 검색 이력';

comment on column public.oasis_prospect_search_history.growth_basis is
    'year_over_year, recent_net 또는 none 고용 증가 판단 기준';
