create extension if not exists pgcrypto;

create table if not exists public.oasis_licensed_businesses (
    id uuid primary key default gen_random_uuid(),
    source_key text not null unique,
    service_key text not null,
    category text not null default '',
    industry_name text not null default '',
    management_no text not null default '',
    company_name text not null,
    address text not null default '',
    province text not null default '',
    district text not null default '',
    phone text not null default '',
    business_status_code text not null default '',
    business_status_name text not null default '',
    is_active boolean not null default true,
    license_date text not null default '',
    close_date text not null default '',
    source_data jsonb not null default '{}'::jsonb,
    last_seen_at timestamptz not null default now(),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

alter table public.oasis_licensed_businesses
    add column if not exists province text not null default '';
alter table public.oasis_licensed_businesses
    add column if not exists district text not null default '';

update public.oasis_licensed_businesses
set
    province = case
        when address like '서울특별시%' or address like '서울시%' then '서울특별시'
        when address like '부산광역시%' or address like '부산시%' then '부산광역시'
        when address like '대구광역시%' or address like '대구시%' then '대구광역시'
        when address like '인천광역시%' or address like '인천시%' then '인천광역시'
        when address like '광주광역시%' then '광주광역시'
        when address like '대전광역시%' or address like '대전시%' then '대전광역시'
        when address like '울산광역시%' or address like '울산시%' then '울산광역시'
        when address like '세종특별자치시%' or address like '세종시%' then '세종특별자치시'
        when address like '경기도%' then '경기도'
        when address like '강원특별자치도%' or address like '강원도%' then '강원특별자치도'
        when address like '충청북도%' or address like '충북 %' then '충청북도'
        when address like '충청남도%' or address like '충남 %' then '충청남도'
        when address like '전북특별자치도%' or address like '전라북도%' or address like '전북 %' then '전북특별자치도'
        when address like '전라남도%' or address like '전남 %' then '전라남도'
        when address like '경상북도%' or address like '경북 %' then '경상북도'
        when address like '경상남도%' or address like '경남 %' then '경상남도'
        when address like '제주특별자치도%' or address like '제주도%' then '제주특별자치도'
        else province
    end,
    district = case
        when address like '세종특별자치시%' or address like '세종시%' then ''
        else split_part(regexp_replace(trim(address), '\s+', ' ', 'g'), ' ', 2)
    end
where province = '' and address <> '';

create index if not exists oasis_licensed_businesses_company_idx
    on public.oasis_licensed_businesses (company_name);
create index if not exists oasis_licensed_businesses_category_idx
    on public.oasis_licensed_businesses (category, industry_name);
create index if not exists oasis_licensed_businesses_active_idx
    on public.oasis_licensed_businesses (is_active, service_key);
create index if not exists oasis_licensed_businesses_region_idx
    on public.oasis_licensed_businesses (province, district, is_active);

create table if not exists public.oasis_license_sync_runs (
    id bigint generated by default as identity primary key,
    service_key text not null,
    page_no integer not null default 1,
    received_count integer not null default 0,
    saved_count integer not null default 0,
    status text not null,
    message text not null default '',
    province text not null default '',
    district text not null default '',
    created_at timestamptz not null default now()
);

alter table public.oasis_license_sync_runs
    add column if not exists province text not null default '';
alter table public.oasis_license_sync_runs
    add column if not exists district text not null default '';

alter table public.oasis_licensed_businesses enable row level security;
alter table public.oasis_license_sync_runs enable row level security;

revoke all on public.oasis_licensed_businesses from anon, authenticated;
revoke all on public.oasis_license_sync_runs from anon, authenticated;
grant all on public.oasis_licensed_businesses to service_role;
grant all on public.oasis_license_sync_runs to service_role;
