-- v9.14.0 AI visit leads. Additive; NO production auto-enable or automatic dialing.
-- Custom oasis_users login: service_role ONLY, with actor/ownership checks in RPC.
begin;
-- Abort safely instead of waiting behind the existing contact collector.
set local lock_timeout = '5s';
set local statement_timeout = '120s';

create table if not exists public.oasis_voice_permissions (
 id uuid primary key default gen_random_uuid(), company_uid text not null,
 phone_e164 text not null, kind text not null check(kind in ('explicit_consent','callback_request')),
 evidence_ref text not null check(length(evidence_ref) between 3 and 500),
 granted_at timestamptz not null, expires_at timestamptz not null, revoked_at timestamptz,
 created_by text not null, created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
 check(expires_at > granted_at), check(phone_e164 ~ '^\+82[0-9]{8,10}$')
);
create index if not exists oasis_voice_permission_lookup on public.oasis_voice_permissions(company_uid,phone_e164,expires_at desc) where revoked_at is null;

create table if not exists public.oasis_voice_suppressions (
 id uuid primary key default gen_random_uuid(), company_uid text not null, phone_e164 text not null,
 reason text not null check(reason in ('do_not_call','wrong_number','declined','revoked')),
 created_by text not null, created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create index if not exists oasis_voice_suppression_company on public.oasis_voice_suppressions(company_uid);
create index if not exists oasis_voice_suppression_phone on public.oasis_voice_suppressions(phone_e164);

create table if not exists public.oasis_voice_jobs (
 id uuid primary key default gen_random_uuid(), request_id text not null, requested_by text not null,
 owner_user_id text not null, assignment_id uuid not null references public.oasis_company_sales_assignments(id),
 company_uid text not null, prospect_id uuid not null references public.oasis_prospect_companies(id),
 contact_id uuid not null references public.oasis_prospect_contacts(id), phone_e164 text not null,
 permission_id uuid not null references public.oasis_voice_permissions(id),
 status text not null default 'queued' check(status in ('queued','approved','dispatching','accepted','in_progress','completed','failed','unknown','cancelled')),
 approved_by text, approved_at timestamptz, dispatch_at timestamptz, dispatch_nonce uuid,
 provider_call_id text unique, connected_at timestamptz, finished_at timestamptz,
 outcome text check(outcome in ('visit_requested','callback_requested','declined','wrong_number','not_representative','do_not_call')),
 visit_at timestamptz, address text not null default '', summary text not null default '', customer_confirmed boolean not null default false,
 visit_confirmed_at timestamptz, visit_confirmed_by text, contact_recorded_at timestamptz,
 last_provider_sequence integer not null default -1, duration_seconds integer, safe_error_code text,
 created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
 unique(requested_by,request_id,company_uid), check(length(request_id) between 8 and 120),
 check(length(address)<=300 and length(summary)<=500)
);
create index if not exists oasis_voice_job_queue on public.oasis_voice_jobs(status,created_at) where status in ('queued','approved');
create index if not exists oasis_voice_job_owner on public.oasis_voice_jobs(owner_user_id,created_at desc);
create index if not exists oasis_voice_job_phone on public.oasis_voice_jobs(phone_e164,created_at desc);
create index if not exists oasis_voice_job_company on public.oasis_voice_jobs(company_uid,created_at desc);
create index if not exists oasis_voice_job_dispatch on public.oasis_voice_jobs(dispatch_at) where dispatch_at is not null;
create index if not exists oasis_voice_job_assignment on public.oasis_voice_jobs(assignment_id);
create index if not exists oasis_voice_job_contact on public.oasis_voice_jobs(contact_id);
create index if not exists oasis_voice_job_prospect on public.oasis_voice_jobs(prospect_id);
create index if not exists oasis_voice_job_permission on public.oasis_voice_jobs(permission_id);

create table if not exists public.oasis_voice_events (
 id bigint generated by default as identity primary key, job_id uuid references public.oasis_voice_jobs(id),
 company_uid text, actor text not null, action text not null, safe_detail jsonb not null default '{}',
 created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create index if not exists oasis_voice_events_job on public.oasis_voice_events(job_id,created_at);

-- Only normalized Korean mobiles/landlines; emergency/short/premium destinations rejected.
create or replace function public.oasis_voice_phone(p_phone text) returns text
language sql immutable set search_path='' as $$
 select case when p ~ '^0(10[0-9]{8}|2[0-9]{7,8}|[3-6][1-5][0-9]{7,8}|70[0-9]{8})$'
 then '+82'||substr(p,2) else null end
 from (select public.oasis_normalize_sales_phone(p_phone) p) x;
$$;

-- Sparse expression index: avoid scanning the phone collector's full contact
-- table for every candidate. This does not change the collector's queue fields.
create index if not exists oasis_voice_existing_optout_phone
 on public.oasis_prospect_contacts(public.oasis_voice_phone(contact_value))
 where (do_not_contact or opt_out_at is not null);

create or replace function public.oasis_voice_target(p_uid text) returns jsonb
language sql stable set search_path='' as $$
 select jsonb_build_object('company_uid',a.company_uid,'assignment_id',a.id,'owner_user_id',a.assigned_user_id,
 'prospect_id',p.id,'contact_id',c.id,'phone_e164',public.oasis_voice_phone(c.contact_value),
 'company_name',p.company_name,'address',p.address,'representative_name',coalesce(p.source_data->>'representative_name',''))
 from public.oasis_company_sales_assignments a
 join public.oasis_prospect_companies p on p.company_uid=a.company_uid and p.owner_user_id=a.assigned_user_id
 join lateral (select c.* from public.oasis_prospect_contacts c where c.prospect_id=p.id
  and c.contact_type in ('phone','mobile','landline','mobile_phone','landline_phone')
  and c.verification_status <> 'rejected' and public.oasis_voice_phone(c.contact_value) is not null
  order by c.is_primary desc,c.confidence desc,c.updated_at desc,c.id limit 1) c on true
 where a.company_uid=p_uid and a.assigned_user_id is not null and public.oasis_sales_actor_is_active(a.assigned_user_id)
 and a.status in ('assigned','pending_contact','contacted','consulting','follow_up')
 and not a.permanently_excluded and not a.migration_conflict and a.released_at is null
 and (a.assignment_expires_at is null or a.assignment_expires_at > now())
 order by (p.id=a.company_id) desc,p.updated_at desc,p.id limit 1;
$$;

create or replace function public.oasis_voice_blocked(p_uid text,p_phone text) returns boolean
language sql stable set search_path='' as $$
 select exists(select 1 from public.oasis_voice_suppressions s where s.company_uid=p_uid or s.phone_e164=p_phone)
 or exists(select 1 from public.oasis_prospect_contacts c join public.oasis_prospect_companies p on p.id=c.prospect_id
  where p.company_uid=p_uid and (c.do_not_contact or c.opt_out_at is not null))
 or exists(select 1 from public.oasis_prospect_contacts c where public.oasis_voice_phone(c.contact_value)=p_phone
  and (c.do_not_contact or c.opt_out_at is not null))
 or exists(select 1 from public.oasis_company_kakao_contact_controls c where c.company_uid=p_uid and c.status in ('opted_out','admin_blocked'));
$$;

create or replace function public.oasis_voice_action(p_current_user_id text,p_action text,p_payload jsonb default '{}')
returns jsonb language plpgsql security invoker set search_path='' as $$
declare
 actor text := lower(btrim(coalesce(p_current_user_id,''))); admin boolean;
 target jsonb; item jsonb; uid text; rows_out jsonb := '[]'; perms public.oasis_voice_permissions%rowtype;
 job public.oasis_voice_jobs%rowtype; candidate record; n integer; offst integer; lim integer;
 kind text; evidence text; start_at timestamptz; end_at timestamptz; request_key text;
 blocked boolean; valid_permission boolean; jobid uuid; result_contact record;
begin
 if not public.oasis_sales_actor_is_active(actor) then return jsonb_build_object('ok',false,'code','NOT_AUTHORIZED'); end if;
 admin := public.oasis_sales_actor_is_admin(actor);
 lim := greatest(1,least(100,coalesce((p_payload->>'limit')::integer,100)));
 offst := greatest(0,least(1000000,coalesce((p_payload->>'offset')::integer,0)));
 if p_action='candidates' then
  n:=0;
  for candidate in select a.company_uid from public.oasis_company_sales_assignments a
   where (admin or a.assigned_user_id=actor) and a.assigned_user_id is not null
   order by a.updated_at desc,a.id limit lim+1 offset offst loop
   n:=n+1;
   if n>lim then exit; end if;
   target := public.oasis_voice_target(candidate.company_uid);
   if target is null then continue; end if;
   blocked := public.oasis_voice_blocked(candidate.company_uid,target->>'phone_e164');
   select * into perms from public.oasis_voice_permissions p where p.company_uid=candidate.company_uid and p.phone_e164=target->>'phone_e164'
    and p.revoked_at is null and p.granted_at<=now() and p.expires_at>now() order by p.created_at desc limit 1;
   valid_permission := perms.id is not null;
   rows_out := rows_out || jsonb_build_array((target-'phone_e164') || jsonb_build_object(
    'phone_masked','***-****-'||right(target->>'phone_e164',4),'permission_kind',perms.kind,
    'permission_valid',valid_permission,'do_not_call',blocked,'eligible',valid_permission and not blocked,
    'assigned_user_id',target->>'owner_user_id'));
  end loop;
  return jsonb_build_object('ok',true,'rows',rows_out,'has_more',n>lim);
 elsif p_action='list_jobs' then
  select coalesce(jsonb_agg(row_data),'[]') into rows_out from (
   select jsonb_build_object('id',j.id,'company_uid',j.company_uid,'company_name',p.company_name,'status',j.status,'outcome',j.outcome,
    'owner_user_id',j.owner_user_id,'created_at',j.created_at,'visit_at',j.visit_at,'address',j.address,'summary',j.summary,
    'visit_confirmed_at',j.visit_confirmed_at,'safe_error_code',j.safe_error_code,'phone_masked','***-****-'||right(j.phone_e164,4)) row_data
   from public.oasis_voice_jobs j join public.oasis_prospect_companies p on p.id=j.prospect_id
   join public.oasis_company_sales_assignments a on a.id=j.assignment_id
   where admin or (j.owner_user_id=actor and a.assigned_user_id=actor)
   order by j.created_at desc,j.id limit lim+1 offset offst) q;
  return jsonb_build_object('ok',true,'rows',(select coalesce(jsonb_agg(value),'[]') from jsonb_array_elements(rows_out) with ordinality v(value,num) where num<=lim),'has_more',jsonb_array_length(rows_out)>lim);
 elsif p_action='list_permissions' then
  select coalesce(jsonb_agg(to_jsonb(q)),'[]') into rows_out from (
   select p.id,p.company_uid,p.kind,p.evidence_ref,p.granted_at,p.expires_at,p.revoked_at,'***-****-'||right(p.phone_e164,4) phone_masked
   from public.oasis_voice_permissions p join public.oasis_company_sales_assignments a on a.company_uid=p.company_uid
   where admin or a.assigned_user_id=actor order by p.created_at desc limit lim+1 offset offst) q;
  return jsonb_build_object('ok',true,'rows',(select coalesce(jsonb_agg(value),'[]') from jsonb_array_elements(rows_out) with ordinality v(value,num) where num<=lim),'has_more',jsonb_array_length(rows_out)>lim);
 end if;
 -- Serialize voice mutations/claim across instances. Batches are deliberately bounded.
 perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended('oasis-voice-queue',0));
 if p_action in ('grant_permission','enqueue') then
  if jsonb_typeof(p_payload->'company_uids') is distinct from 'array' then raise exception 'INVALID_INPUT'; end if;
  n := jsonb_array_length(p_payload->'company_uids');
  if n<1 or n>(case when p_action='enqueue' then 30 else 100 end) then raise exception 'INVALID_INPUT'; end if;
  if p_action='grant_permission' then
   kind:=p_payload->>'kind'; evidence:=btrim(coalesce(p_payload->>'evidence_ref',''));
   start_at:=(p_payload->>'granted_at')::timestamptz; end_at:=(p_payload->>'expires_at')::timestamptz;
   if kind is null or kind not in ('explicit_consent','callback_request') or length(evidence)<3 or length(evidence)>500 or start_at is null or end_at is null
    or start_at>now() or end_at<=now() or end_at>now()+interval '2 years' or end_at<=start_at
    or (kind='callback_request' and end_at>now()+interval '31 days') then raise exception 'INVALID_INPUT'; end if;
  else
   request_key:=p_payload->>'request_id';
   if request_key is null or request_key !~ '^[A-Za-z0-9._:-]{8,120}$' then raise exception 'INVALID_INPUT'; end if;
  end if;
  for uid in select distinct value from jsonb_array_elements_text(p_payload->'company_uids') loop
   target:=public.oasis_voice_target(uid);
   if target is null or (not admin and target->>'owner_user_id'<>actor) then raise exception 'NOT_AUTHORIZED'; end if;
   if public.oasis_voice_blocked(uid,target->>'phone_e164') then raise exception 'DO_NOT_CALL'; end if;
   if p_action='grant_permission' then
    -- Append evidence history, never overwrite previous proof and never unsuppress a number.
    insert into public.oasis_voice_permissions(company_uid,phone_e164,kind,evidence_ref,granted_at,expires_at,created_by)
     values(uid,target->>'phone_e164',kind,evidence,start_at,end_at,actor) returning * into perms;
    rows_out:=rows_out||jsonb_build_array(jsonb_build_object('company_uid',uid,'permission_id',perms.id));
   else
    select * into job from public.oasis_voice_jobs j where j.requested_by=actor and j.request_id=request_key and j.company_uid=uid;
    if job.id is not null then
     rows_out:=rows_out||jsonb_build_array(jsonb_build_object('id',job.id,'status',job.status)); continue;
    end if;
    select * into perms from public.oasis_voice_permissions p where p.company_uid=uid and p.phone_e164=target->>'phone_e164'
     and p.revoked_at is null and p.granted_at<=now() and p.expires_at>now() order by p.created_at desc limit 1;
    if perms.id is null then raise exception 'CONSENT_REQUIRED'; end if;
    if exists(select 1 from public.oasis_voice_jobs j where (j.company_uid=uid or j.phone_e164=target->>'phone_e164')
     and (j.status in ('queued','approved','dispatching','accepted','in_progress','unknown') or j.dispatch_at>now()-interval '7 days'
      or j.outcome in ('visit_requested','callback_requested'))) then raise exception 'DUPLICATE'; end if;
    insert into public.oasis_voice_jobs(requested_by,request_id,owner_user_id,assignment_id,company_uid,prospect_id,contact_id,phone_e164,permission_id)
     values(actor,request_key,target->>'owner_user_id',(target->>'assignment_id')::uuid,uid,(target->>'prospect_id')::uuid,(target->>'contact_id')::uuid,target->>'phone_e164',perms.id) returning * into job;
    rows_out:=rows_out||jsonb_build_array(jsonb_build_object('id',job.id,'status',job.status));
   end if;
   insert into public.oasis_voice_events(company_uid,actor,action) values(uid,actor,p_action);
  end loop;
  return jsonb_build_object('ok',true,'rows',rows_out);
 elsif p_action in ('revoke_permission','do_not_call') then
  uid:=p_payload->>'company_uid'; target:=public.oasis_voice_target(uid);
  if target is null or (not admin and target->>'owner_user_id'<>actor) then raise exception 'NOT_AUTHORIZED'; end if;
  update public.oasis_voice_permissions p set revoked_at=now(),updated_at=now() where p.company_uid=uid and p.revoked_at is null;
  insert into public.oasis_voice_suppressions(company_uid,phone_e164,reason,created_by)
   values(uid,target->>'phone_e164',case when p_action='do_not_call' then 'do_not_call' else 'revoked' end,actor);
  update public.oasis_voice_jobs j set status='cancelled',finished_at=now(),updated_at=now() where (j.company_uid=uid or j.phone_e164=target->>'phone_e164') and j.status in ('queued','approved');
  insert into public.oasis_voice_events(company_uid,actor,action) values(uid,actor,p_action);
  return jsonb_build_object('ok',true);
 elsif p_action in ('approve','cancel','confirm_visit','reconcile') then
  jobid:=(p_payload->>'job_id')::uuid;
  select * into job from public.oasis_voice_jobs j where j.id=jobid for update;
  if job.id is null or not (admin or (job.owner_user_id=actor and exists(select 1 from public.oasis_company_sales_assignments a where a.id=job.assignment_id and a.assigned_user_id=actor))) then raise exception 'NOT_AUTHORIZED'; end if;
  if p_action='approve' then
   if not admin then raise exception 'NOT_AUTHORIZED'; end if;
   if job.status<>'queued' then raise exception 'INVALID_STATE'; end if;
   update public.oasis_voice_jobs set status='approved',approved_by=actor,approved_at=now(),updated_at=now() where id=job.id;
  elsif p_action='cancel' then
   if job.status not in ('queued','approved') then raise exception 'INVALID_STATE'; end if;
   update public.oasis_voice_jobs set status='cancelled',finished_at=now(),updated_at=now() where id=job.id;
  elsif p_action='reconcile' then
   if not admin then raise exception 'NOT_AUTHORIZED'; end if;
   if job.status<>'unknown' or length(btrim(coalesce(p_payload->>'reason','')))<3
    or coalesce(p_payload->>'resolution','') not in ('confirmed_ended','confirmed_not_sent') then raise exception 'INVALID_INPUT'; end if;
   if job.provider_call_id is not null and p_payload->>'resolution'='confirmed_not_sent' then raise exception 'INVALID_INPUT'; end if;
   -- Manual provider console reconciliation, never returns the job to queue.
   -- Any suppression created earlier remains permanently effective.
   update public.oasis_voice_jobs set status=case when p_payload->>'resolution'='confirmed_ended' then 'completed' else 'failed' end,
    finished_at=now(),safe_error_code='MANUALLY_RECONCILED',updated_at=now() where id=job.id;
  else
   if job.outcome<>'visit_requested' or job.visit_at is null or job.visit_at<=now() or job.visit_confirmed_at is not null
    or length(btrim(coalesce(p_payload->>'reason','')))<3 then raise exception 'INVALID_STATE'; end if;
   if exists(select 1 from public.oasis_voice_jobs j where j.id<>job.id and j.owner_user_id=job.owner_user_id and j.visit_confirmed_at is not null
    and abs(extract(epoch from(j.visit_at-job.visit_at)))<3600) then raise exception 'APPOINTMENT_CONFLICT'; end if;
   select * into result_contact from public.oasis_record_company_sales_contact(actor,job.prospect_id,job.company_uid,'phone','consultation_scheduled',
    'AI 방문요청 담당자 확인',job.visit_at,now(),'voice-confirm:'||job.id::text);
   if not coalesce(result_contact.success,false) then raise exception 'TARGET_CHANGED'; end if;
   update public.oasis_voice_jobs set visit_confirmed_at=now(),visit_confirmed_by=actor,updated_at=now() where id=job.id;
  end if;
  insert into public.oasis_voice_events(job_id,company_uid,actor,action,safe_detail) values(job.id,job.company_uid,actor,p_action,
   case when p_action in ('confirm_visit','reconcile') then jsonb_build_object('reason_hash',md5(p_payload->>'reason'),'resolution',p_payload->>'resolution') else '{}'::jsonb end);
  return jsonb_build_object('ok',true);
 end if;
 return jsonb_build_object('ok',false,'code','INVALID_INPUT');
exception when raise_exception then return jsonb_build_object('ok',false,'code',sqlerrm);
 when invalid_text_representation or datetime_field_overflow or invalid_datetime_format or numeric_value_out_of_range then return jsonb_build_object('ok',false,'code','INVALID_INPUT');
end;
$$;

create or replace function public.oasis_voice_worker(p_action text,p_payload jsonb default '{}')
returns jsonb language plpgsql security invoker set search_path='' as $$
declare job public.oasis_voice_jobs%rowtype; target jsonb; perms public.oasis_voice_permissions%rowtype;
 code text; provider_id text; new_status text; outcome_value text; when_at timestamptz;
 contact_result text; r record; seq integer; daily integer;
begin
 perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended('oasis-voice-queue',0));
 if p_action='claim' then
  -- Unknown outcomes block more dialing until investigated, never silently retry.
  update public.oasis_voice_jobs set status='unknown',safe_error_code='STALE_DISPATCH',updated_at=now()
   where status in ('dispatching','accepted','in_progress') and dispatch_at<now()-interval '10 minutes';
  if extract(isodow from now() at time zone 'Asia/Seoul')>5 or extract(hour from now() at time zone 'Asia/Seoul') not between 9 and 17 then
   return jsonb_build_object('ok',true,'code','OUTSIDE_HOURS'); end if;
  daily:=greatest(1,least(100,coalesce((p_payload->>'daily_limit')::integer,20)));
  if (select count(*) from public.oasis_voice_jobs where dispatch_at>=(date_trunc('day',now() at time zone 'Asia/Seoul') at time zone 'Asia/Seoul'))>=daily then
   return jsonb_build_object('ok',true,'code','DAILY_LIMIT'); end if;
  if exists(select 1 from public.oasis_voice_jobs where status in ('dispatching','accepted','in_progress','unknown')) then
   return jsonb_build_object('ok',true,'code','BUSY'); end if;
  select * into job from public.oasis_voice_jobs where status='approved' order by created_at,id limit 1 for update skip locked;
  if job.id is null then return jsonb_build_object('ok',true,'code','EMPTY'); end if;
  target:=public.oasis_voice_target(job.company_uid);
  select * into perms from public.oasis_voice_permissions where id=job.permission_id;
  if target is null or target->>'owner_user_id'<>job.owner_user_id or target->>'phone_e164'<>job.phone_e164
   or (target->>'contact_id')::uuid<>job.contact_id or job.approved_at<now()-interval '24 hours'
   or not public.oasis_sales_actor_is_admin(job.approved_by)
   or perms.revoked_at is not null or perms.granted_at>now() or perms.expires_at<=now()
   or public.oasis_voice_blocked(job.company_uid,job.phone_e164) then
   update public.oasis_voice_jobs set status='cancelled',safe_error_code='TARGET_CHANGED',finished_at=now(),updated_at=now() where id=job.id;
   insert into public.oasis_voice_events(job_id,company_uid,actor,action) values(job.id,job.company_uid,'worker','preflight_cancelled');
   return jsonb_build_object('ok',true,'code','TARGET_CHANGED');
  end if;
  update public.oasis_voice_jobs set status='dispatching',dispatch_at=now(),dispatch_nonce=gen_random_uuid(),updated_at=now() where id=job.id returning * into job;
  insert into public.oasis_voice_events(job_id,company_uid,actor,action) values(job.id,job.company_uid,'worker','dispatch_claimed');
  return jsonb_build_object('ok',true,'job',target||to_jsonb(job));
 end if;
 select * into job from public.oasis_voice_jobs where id=(p_payload->>'job_id')::uuid for update;
 if job.id is null then return jsonb_build_object('ok',false,'code','INVALID_INPUT'); end if;
 provider_id:=p_payload->>'provider_call_id';
 if job.provider_call_id is not null and provider_id is distinct from job.provider_call_id then
  return jsonb_build_object('ok',false,'code','PROVIDER_MISMATCH'); end if;
 if p_action in ('connect','status','result','mark_dispatched') and (provider_id is null or provider_id !~ '^CA[0-9a-fA-F]{32}$') then
  return jsonb_build_object('ok',false,'code','PROVIDER_MISMATCH'); end if;
 if job.provider_call_id is null and p_action in ('connect','status','mark_dispatched') then
  if job.status<>'dispatching' then return jsonb_build_object('ok',false,'code','INVALID_STATE'); end if;
  update public.oasis_voice_jobs set provider_call_id=provider_id,updated_at=now() where id=job.id returning * into job;
 end if;
 if p_action in ('get_job','connect') then
  target:=public.oasis_voice_target(job.company_uid);
  select * into perms from public.oasis_voice_permissions where id=job.permission_id;
  if target is null or target->>'owner_user_id'<>job.owner_user_id or target->>'phone_e164'<>job.phone_e164
   or perms.revoked_at is not null or perms.expires_at<=now() or public.oasis_voice_blocked(job.company_uid,job.phone_e164)
   or job.status not in ('dispatching','accepted','in_progress') then return jsonb_build_object('ok',false,'code','TARGET_CHANGED'); end if;
  if p_action='connect' then
   if job.connected_at is not null or (p_payload->>'dispatch_nonce')::uuid is distinct from job.dispatch_nonce then
    return jsonb_build_object('ok',false,'code','PROVIDER_MISMATCH'); end if;
   update public.oasis_voice_jobs set connected_at=now(),status='in_progress',updated_at=now() where id=job.id returning * into job;
  end if;
  return jsonb_build_object('ok',true,'job',target||to_jsonb(job));
 elsif p_action='mark_dispatched' then
  update public.oasis_voice_jobs set status='accepted',updated_at=now() where id=job.id and status='dispatching';
 elsif p_action in ('mark_unknown','mark_failed','bridge_error') then
  if p_action='bridge_error' and p_payload->>'error_code'='DO_NOT_CALL_SAVE_FAILED' then
   insert into public.oasis_voice_suppressions(company_uid,phone_e164,reason,created_by)
    values(job.company_uid,job.phone_e164,'do_not_call','voice-safety');
   update public.oasis_voice_jobs set status='unknown',safe_error_code='DO_NOT_CALL_SAVE_FAILED',updated_at=now() where id=job.id;
   update public.oasis_voice_jobs set status='cancelled',finished_at=now(),updated_at=now()
    where id<>job.id and (company_uid=job.company_uid or phone_e164=job.phone_e164) and status in ('queued','approved');
  else
  update public.oasis_voice_jobs set status=case when p_action='mark_failed' then 'failed' else 'unknown' end,
   safe_error_code=case when p_action='bridge_error' then 'BRIDGE_FAILED' when p_action='mark_failed' then 'PROVIDER_REJECTED' else 'DISPATCH_UNKNOWN' end,
   updated_at=now() where id=job.id and status not in ('completed','failed','cancelled');
  end if;
 elsif p_action='status' then
  seq:=coalesce((p_payload->>'sequence_number')::integer,-1);
  if seq<job.last_provider_sequence then return jsonb_build_object('ok',true); end if;
  new_status:=case p_payload->>'status' when 'completed' then 'completed' when 'busy' then 'failed' when 'failed' then 'failed' when 'no-answer' then 'failed' when 'canceled' then 'cancelled' else null end;
  if new_status is not null and job.status not in ('completed','failed','cancelled') and coalesce(job.safe_error_code,'')<>'DO_NOT_CALL_SAVE_FAILED' then
   update public.oasis_voice_jobs set status=new_status,finished_at=now(),last_provider_sequence=seq,
    duration_seconds=greatest(0,least(7200,coalesce((p_payload->>'duration_seconds')::integer,0))),updated_at=now() where id=job.id;
  end if;
 elsif p_action='result' then
  if job.connected_at is null or job.provider_call_id is null or job.status not in ('in_progress','completed','unknown') then raise exception 'INVALID_STATE'; end if;
  outcome_value:=p_payload->>'outcome';
  if outcome_value is null or outcome_value not in ('visit_requested','callback_requested','declined','wrong_number','not_representative','do_not_call') then raise exception 'INVALID_RESULT'; end if;
  if job.outcome='do_not_call' then return jsonb_build_object('ok',true); end if;
  -- A late opt-out always wins; other repeated tool calls never duplicate contact logs.
  if job.outcome is not null and outcome_value<>'do_not_call' then return jsonb_build_object('ok',true,'code','DUPLICATE'); end if;
  if outcome_value in ('visit_requested','callback_requested') then
   if (p_payload->>'customer_confirmed') is distinct from 'true' or coalesce(p_payload->>'visit_at','') !~ '(Z|[+-][0-9]{2}:[0-9]{2})$' then raise exception 'INVALID_RESULT'; end if;
   when_at:=(p_payload->>'visit_at')::timestamptz;
   if when_at<=now() or when_at>now()+interval '90 days' or extract(isodow from when_at at time zone 'Asia/Seoul')>5
    or extract(hour from when_at at time zone 'Asia/Seoul') not between 9 and 17 or (outcome_value='visit_requested' and length(btrim(coalesce(p_payload->>'address','')))<5) then raise exception 'INVALID_RESULT'; end if;
  end if;
  if outcome_value in ('do_not_call','wrong_number','declined') then
   insert into public.oasis_voice_suppressions(company_uid,phone_e164,reason,created_by) values(job.company_uid,job.phone_e164,outcome_value,'voice-customer');
   update public.oasis_voice_jobs set status='cancelled',finished_at=now(),updated_at=now() where id<>job.id and (company_uid=job.company_uid or phone_e164=job.phone_e164) and status in ('queued','approved');
  end if;
  update public.oasis_voice_jobs set outcome=outcome_value,visit_at=when_at,address=left(coalesce(p_payload->>'address',''),300),
   summary=left(coalesce(p_payload->>'summary',''),500),customer_confirmed=coalesce((p_payload->>'customer_confirmed')::boolean,false),
   visit_confirmed_at=case when outcome_value='do_not_call' then null else visit_confirmed_at end,
   visit_confirmed_by=case when outcome_value='do_not_call' then null else visit_confirmed_by end,updated_at=now() where id=job.id;
  if job.contact_recorded_at is null and exists(select 1 from public.oasis_company_sales_assignments where id=job.assignment_id and assigned_user_id=job.owner_user_id) then
   begin
   contact_result:=case outcome_value when 'callback_requested' then 'follow_up_requested' when 'do_not_call' then 'not_interested' when 'declined' then 'not_interested' when 'wrong_number' then 'bad_number' else 'connected' end;
   select * into r from public.oasis_record_company_sales_contact(job.owner_user_id,job.prospect_id,job.company_uid,'phone',contact_result,
    'AI 상담 결과: '||outcome_value,when_at,now(),'voice:'||job.id::text);
   if coalesce(r.success,false) then
    update public.oasis_voice_jobs set contact_recorded_at=now() where id=job.id;
   else
    update public.oasis_voice_jobs set safe_error_code='CONTACT_SYNC_PENDING',updated_at=now() where id=job.id;
   end if;
   exception when others then
    -- A CRM contact-log outage must NOT undo a customer opt-out or visit request.
    update public.oasis_voice_jobs set safe_error_code='CONTACT_SYNC_PENDING',updated_at=now() where id=job.id;
   end;
  end if;
 else return jsonb_build_object('ok',false,'code','INVALID_INPUT');
 end if;
 insert into public.oasis_voice_events(job_id,company_uid,actor,action,safe_detail) values(job.id,job.company_uid,'worker',p_action,
  jsonb_build_object('outcome',outcome_value,'status',new_status));
 return jsonb_build_object('ok',true);
exception when raise_exception then return jsonb_build_object('ok',false,'code',sqlerrm);
 when invalid_text_representation or datetime_field_overflow or invalid_datetime_format or numeric_value_out_of_range then return jsonb_build_object('ok',false,'code','INVALID_INPUT');
end;
$$;

-- No auth.uid policy: this app uses custom oasis_users, not Supabase Auth.
-- Browser roles get neither table access nor RPC execution. Server checks actor.
alter table public.oasis_voice_permissions enable row level security;
alter table public.oasis_voice_suppressions enable row level security;
alter table public.oasis_voice_jobs enable row level security;
alter table public.oasis_voice_events enable row level security;
revoke all on public.oasis_voice_permissions,public.oasis_voice_suppressions,public.oasis_voice_jobs,public.oasis_voice_events from public,anon,authenticated,service_role;
grant select,insert,update on public.oasis_voice_permissions,public.oasis_voice_jobs to service_role;
grant select,insert on public.oasis_voice_suppressions,public.oasis_voice_events to service_role;
grant usage,select on sequence public.oasis_voice_events_id_seq to service_role;
revoke all on function public.oasis_voice_phone(text),public.oasis_voice_target(text),public.oasis_voice_blocked(text,text),public.oasis_voice_action(text,text,jsonb),public.oasis_voice_worker(text,jsonb) from public,anon,authenticated;
grant execute on function public.oasis_voice_phone(text),public.oasis_voice_target(text),public.oasis_voice_blocked(text,text),public.oasis_voice_action(text,text,jsonb),public.oasis_voice_worker(text,jsonb) to service_role;
commit;
