begin;

-- 사업자등록번호로 정확히 조회한 업체의 개별 배정 신청을 관리한다.
-- 원문 휴대전화는 신청 테이블과 사용자 조회 결과에 저장하거나 반환하지 않는다.
create table if not exists public.oasis_specific_company_db_requests (
    id uuid primary key default extensions.gen_random_uuid(),
    requested_user_id text not null,
    company_uid text not null,
    business_no text not null,
    source_contact_key text not null,
    status text not null default 'pending',
    decision_reason text not null default '',
    decided_by_user_id text,
    assignment_id uuid references public.oasis_company_sales_assignments(id)
        on delete set null,
    prospect_id uuid references public.oasis_prospect_companies(id)
        on delete set null,
    requested_at timestamptz not null default now(),
    decided_at timestamptz,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint oasis_specific_company_db_requests_uid_check
        check (public.oasis_is_valid_company_uid(company_uid)),
    constraint oasis_specific_company_db_requests_business_no_check
        check (business_no ~ '^[0-9]{10}$'),
    constraint oasis_specific_company_db_requests_status_check
        check (status in ('pending', 'approved', 'rejected', 'cancelled'))
);

create unique index if not exists
    idx_oasis_specific_company_db_requests_one_pending_company
on public.oasis_specific_company_db_requests (company_uid)
where status = 'pending';

create index if not exists idx_oasis_specific_company_db_requests_user
    on public.oasis_specific_company_db_requests (
        requested_user_id, requested_at desc, id
    );

create index if not exists idx_oasis_specific_company_db_requests_admin
    on public.oasis_specific_company_db_requests (status, requested_at, id);

create index if not exists idx_oasis_employment_contacts_business_no_exact
    on public.oasis_employment_contacts (business_no)
    where business_no ~ '^[0-9]{10}$';

create table if not exists public.oasis_specific_company_db_request_events (
    id bigint generated by default as identity primary key,
    request_id uuid not null
        references public.oasis_specific_company_db_requests(id)
        on delete cascade,
    actor_user_id text not null,
    action text not null,
    reason text not null default '',
    created_at timestamptz not null default now(),
    constraint oasis_specific_company_db_request_events_action_check
        check (action in ('requested', 'approved', 'rejected', 'cancelled'))
);

create index if not exists idx_oasis_specific_company_db_request_events_request
    on public.oasis_specific_company_db_request_events (
        request_id, created_at, id
    );

alter table public.oasis_specific_company_db_requests
    enable row level security;
alter table public.oasis_specific_company_db_request_events
    enable row level security;

revoke all on table public.oasis_specific_company_db_requests
    from public, anon, authenticated;
revoke all on table public.oasis_specific_company_db_request_events
    from public, anon, authenticated;
grant select, insert, update on table public.oasis_specific_company_db_requests
    to service_role;
grant select, insert on table public.oasis_specific_company_db_request_events
    to service_role;

create or replace function public.oasis_search_company_db_by_business_no(
    p_current_user_id text,
    p_business_no text
)
returns table (
    found boolean,
    code text,
    message text,
    company_uid text,
    company_name text,
    business_no text,
    business_type text,
    industry_name text,
    address text,
    masked_mobile_phone text,
    landline_phone text,
    has_mobile_phone boolean,
    has_landline_phone boolean,
    requestable boolean,
    request_status text,
    request_id uuid
)
language plpgsql
stable
security invoker
set search_path = public, pg_temp
as $$
declare
    v_actor text := lower(btrim(coalesce(p_current_user_id, '')));
    v_business_no text := public.oasis_sales_digits(p_business_no);
    v_contact public.oasis_employment_contacts%rowtype;
    v_assignment public.oasis_company_sales_assignments%rowtype;
    v_request public.oasis_specific_company_db_requests%rowtype;
    v_uid text;
    v_mobile_digits text;
    v_request_status text := 'available';
    v_requestable boolean := false;
begin
    if not public.oasis_sales_actor_is_active(v_actor) then
        raise exception using
            errcode = '42501',
            message = 'OASIS_SALES_USER_NOT_AUTHORIZED';
    end if;
    if length(v_business_no) <> 10 then
        return query select
            false, 'invalid_input',
            '사업자등록번호 10자리를 입력해 주세요.',
            null::text, null::text, null::text, null::text,
            null::text, null::text, null::text, null::text,
            false, false, false, 'invalid', null::uuid;
        return;
    end if;

    select c.* into v_contact
    from public.oasis_employment_contacts c
    where c.business_no = v_business_no
      and (
          coalesce(c.has_mobile_phone, false)
          or coalesce(c.has_landline_phone, false)
      )
    order by
        coalesce(c.has_mobile_phone, false) desc,
        coalesce(c.has_landline_phone, false) desc,
        c.phone_checked_at desc nulls last,
        c.checked_at desc nulls last,
        c.contact_key
    limit 1;

    if v_contact.contact_key is null then
        return query select
            false, 'not_found',
            '해당 사업자등록번호로 신청 가능한 전화번호 DB를 찾지 못했습니다.',
            null::text, null::text, v_business_no, null::text,
            null::text, null::text, null::text, null::text,
            false, false, false, 'not_found', null::uuid;
        return;
    end if;

    v_uid := 'business:' || v_business_no;
    v_mobile_digits := regexp_replace(
        coalesce(v_contact.mobile_phone, ''), '[^0-9]', '', 'g'
    );

    select a.* into v_assignment
    from public.oasis_company_sales_assignments a
    where a.company_uid = v_uid;

    select r.* into v_request
    from public.oasis_specific_company_db_requests r
    where r.company_uid = v_uid
      and r.status = 'pending'
    order by r.requested_at, r.id
    limit 1;

    if v_assignment.company_uid is not null
       and v_assignment.assigned_user_id = v_actor
       and v_assignment.status <> 'unassigned' then
        v_request_status := 'already_owned';
    elsif v_assignment.company_uid is not null
       and not (
           v_assignment.status = 'unassigned'
           and v_assignment.assigned_user_id is null
           and coalesce(v_assignment.permanently_excluded, false) is false
           and coalesce(v_assignment.migration_conflict, false) is false
       ) then
        v_request_status := case
            when coalesce(v_assignment.permanently_excluded, false)
                then 'permanently_excluded'
            else 'unavailable'
        end;
    elsif v_request.id is not null then
        v_request_status := case
            when v_request.requested_user_id = v_actor then 'pending_own'
            else 'pending_other'
        end;
    else
        v_request_status := 'available';
        v_requestable := true;
    end if;

    return query select
        true,
        'found',
        case v_request_status
            when 'available' then '신청 가능한 업체입니다.'
            when 'pending_own' then '관리자 승인 대기 중인 업체입니다.'
            when 'pending_other' then '현재 다른 신청을 검토 중인 업체입니다.'
            when 'already_owned' then '이미 내 DB에 배정된 업체입니다.'
            when 'permanently_excluded' then '영구 제외된 업체입니다.'
            else '현재 신청할 수 없는 업체입니다.'
        end,
        v_uid,
        coalesce(nullif(btrim(v_contact.company_name), ''), '업체명 미확인'),
        v_business_no,
        case
            when public.oasis_is_stock_company(v_contact.company_name)
                then 'corporate'
            else 'individual'
        end,
        coalesce(v_contact.industry_name, ''),
        coalesce(v_contact.address, ''),
        case
            when length(v_mobile_digits) between 10 and 11
                then substr(v_mobile_digits, 1, 3)
                     || '-****-' || right(v_mobile_digits, 4)
            when coalesce(v_contact.has_mobile_phone, false)
                then '휴대폰 번호 보유'
            else ''
        end,
        coalesce(v_contact.landline_phone, ''),
        coalesce(v_contact.has_mobile_phone, false),
        coalesce(v_contact.has_landline_phone, false),
        v_requestable,
        v_request_status,
        case
            when v_request.requested_user_id = v_actor then v_request.id
            else null::uuid
        end;
end;
$$;

create or replace function public.oasis_submit_specific_company_db_request(
    p_current_user_id text,
    p_business_no text,
    p_session_id text default null
)
returns table (
    success boolean,
    code text,
    message text,
    request_id uuid,
    status text
)
language plpgsql
volatile
security invoker
set search_path = public, extensions, pg_temp
as $$
declare
    v_actor text := lower(btrim(coalesce(p_current_user_id, '')));
    v_business_no text := public.oasis_sales_digits(p_business_no);
    v_contact public.oasis_employment_contacts%rowtype;
    v_assignment public.oasis_company_sales_assignments%rowtype;
    v_existing public.oasis_specific_company_db_requests%rowtype;
    v_saved public.oasis_specific_company_db_requests%rowtype;
    v_uid text;
begin
    if not public.oasis_sales_actor_is_active(v_actor) then
        raise exception using
            errcode = '42501',
            message = 'OASIS_SALES_USER_NOT_AUTHORIZED';
    end if;
    if length(v_business_no) <> 10 then
        return query select false, 'invalid_input',
            '사업자등록번호 10자리를 입력해 주세요.',
            null::uuid, null::text;
        return;
    end if;

    v_uid := 'business:' || v_business_no;
    perform pg_advisory_xact_lock(
        hashtextextended('oasis-specific-db:' || v_uid, 0)
    );

    select c.* into v_contact
    from public.oasis_employment_contacts c
    where c.business_no = v_business_no
      and (
          coalesce(c.has_mobile_phone, false)
          or coalesce(c.has_landline_phone, false)
      )
    order by
        coalesce(c.has_mobile_phone, false) desc,
        coalesce(c.has_landline_phone, false) desc,
        c.phone_checked_at desc nulls last,
        c.checked_at desc nulls last,
        c.contact_key
    limit 1;

    if v_contact.contact_key is null then
        return query select false, 'not_found',
            '해당 사업자등록번호로 신청 가능한 전화번호 DB를 찾지 못했습니다.',
            null::uuid, null::text;
        return;
    end if;

    select a.* into v_assignment
    from public.oasis_company_sales_assignments a
    where a.company_uid = v_uid
    for update;

    if v_assignment.company_uid is not null
       and not (
           v_assignment.status = 'unassigned'
           and v_assignment.assigned_user_id is null
           and coalesce(v_assignment.permanently_excluded, false) is false
           and coalesce(v_assignment.migration_conflict, false) is false
       ) then
        return query select false, 'unavailable',
            case
                when v_assignment.assigned_user_id = v_actor
                    then '이미 내 DB에 배정된 업체입니다.'
                else '현재 신청할 수 없는 업체입니다.'
            end,
            null::uuid, null::text;
        return;
    end if;

    select r.* into v_existing
    from public.oasis_specific_company_db_requests r
    where r.company_uid = v_uid
      and r.status = 'pending'
    order by r.requested_at, r.id
    limit 1
    for update;

    if v_existing.id is not null then
        return query select
            v_existing.requested_user_id = v_actor,
            case when v_existing.requested_user_id = v_actor
                then 'already_requested' else 'pending_other' end,
            case when v_existing.requested_user_id = v_actor
                then '이미 관리자 승인 대기 중인 업체입니다.'
                else '현재 다른 신청을 검토 중인 업체입니다.' end,
            case when v_existing.requested_user_id = v_actor
                then v_existing.id else null::uuid end,
            v_existing.status;
        return;
    end if;

    insert into public.oasis_specific_company_db_requests (
        requested_user_id,
        company_uid,
        business_no,
        source_contact_key
    ) values (
        v_actor,
        v_uid,
        v_business_no,
        v_contact.contact_key
    ) returning * into v_saved;

    insert into public.oasis_specific_company_db_request_events (
        request_id, actor_user_id, action, reason
    ) values (
        v_saved.id, v_actor, 'requested',
        left(coalesce(p_session_id, ''), 500)
    );

    return query select true, 'requested',
        'DB 신청을 접수했습니다. 관리자 승인 후 내 DB에 배정됩니다.',
        v_saved.id, v_saved.status;
end;
$$;

create or replace function public.oasis_list_user_specific_company_db_requests(
    p_current_user_id text,
    p_limit integer default 20
)
returns table (
    request_id uuid,
    company_name text,
    business_no text,
    masked_mobile_phone text,
    has_mobile_phone boolean,
    has_landline_phone boolean,
    status text,
    decision_reason text,
    requested_at timestamptz,
    decided_at timestamptz
)
language plpgsql
stable
security invoker
set search_path = public, pg_temp
as $$
declare
    v_actor text := lower(btrim(coalesce(p_current_user_id, '')));
begin
    if not public.oasis_sales_actor_is_active(v_actor) then
        raise exception using
            errcode = '42501',
            message = 'OASIS_SALES_USER_NOT_AUTHORIZED';
    end if;

    return query
    select
        r.id,
        coalesce(nullif(btrim(c.company_name), ''), '업체명 미확인'),
        r.business_no,
        case
            when length(regexp_replace(coalesce(c.mobile_phone, ''), '[^0-9]', '', 'g'))
                    between 10 and 11
                then substr(
                        regexp_replace(c.mobile_phone, '[^0-9]', '', 'g'),
                        1, 3
                     ) || '-****-' || right(
                        regexp_replace(c.mobile_phone, '[^0-9]', '', 'g'),
                        4
                     )
            when coalesce(c.has_mobile_phone, false)
                then '휴대폰 번호 보유'
            else ''
        end,
        coalesce(c.has_mobile_phone, false),
        coalesce(c.has_landline_phone, false),
        r.status,
        r.decision_reason,
        r.requested_at,
        r.decided_at
    from public.oasis_specific_company_db_requests r
    left join public.oasis_employment_contacts c
      on c.contact_key = r.source_contact_key
    where r.requested_user_id = v_actor
    order by r.requested_at desc, r.id desc
    limit greatest(1, least(coalesce(p_limit, 20), 100));
end;
$$;

create or replace function public.oasis_list_admin_specific_company_db_requests(
    p_current_user_id text,
    p_statuses text[] default null,
    p_limit integer default 200
)
returns table (
    request_id uuid,
    requested_user_id text,
    requested_user_name text,
    company_name text,
    business_no text,
    business_type text,
    industry_name text,
    address text,
    masked_mobile_phone text,
    landline_phone text,
    has_mobile_phone boolean,
    has_landline_phone boolean,
    status text,
    decision_reason text,
    requested_at timestamptz,
    decided_at timestamptz
)
language plpgsql
stable
security invoker
set search_path = public, pg_temp
as $$
begin
    if not public.oasis_sales_actor_is_admin(p_current_user_id) then
        raise exception using
            errcode = '42501',
            message = 'OASIS_SALES_ADMIN_REQUIRED';
    end if;

    return query
    select
        r.id,
        r.requested_user_id,
        coalesce(u.name, r.requested_user_id),
        coalesce(nullif(btrim(c.company_name), ''), '업체명 미확인'),
        r.business_no,
        case
            when public.oasis_is_stock_company(c.company_name)
                then 'corporate'
            else 'individual'
        end,
        coalesce(c.industry_name, ''),
        coalesce(c.address, ''),
        case
            when length(regexp_replace(coalesce(c.mobile_phone, ''), '[^0-9]', '', 'g'))
                    between 10 and 11
                then substr(
                        regexp_replace(c.mobile_phone, '[^0-9]', '', 'g'),
                        1, 3
                     ) || '-****-' || right(
                        regexp_replace(c.mobile_phone, '[^0-9]', '', 'g'),
                        4
                     )
            when coalesce(c.has_mobile_phone, false)
                then '휴대폰 번호 보유'
            else ''
        end,
        coalesce(c.landline_phone, ''),
        coalesce(c.has_mobile_phone, false),
        coalesce(c.has_landline_phone, false),
        r.status,
        r.decision_reason,
        r.requested_at,
        r.decided_at
    from public.oasis_specific_company_db_requests r
    left join public.oasis_employment_contacts c
      on c.contact_key = r.source_contact_key
    left join public.oasis_users u
      on lower(u.user_id) = lower(r.requested_user_id)
    where coalesce(cardinality(p_statuses), 0) = 0
       or r.status = any(p_statuses)
    order by
        case when r.status = 'pending' then 0 else 1 end,
        r.requested_at,
        r.id
    limit greatest(1, least(coalesce(p_limit, 200), 1000));
end;
$$;

create or replace function public.oasis_admin_review_specific_company_db_request(
    p_current_user_id text,
    p_request_id uuid,
    p_action text,
    p_reason text default '',
    p_session_id text default null
)
returns table (
    success boolean,
    code text,
    message text,
    request_id uuid,
    status text,
    assignment_id uuid
)
language plpgsql
volatile
security invoker
set search_path = public, extensions, pg_temp
as $$
declare
    v_admin text := lower(btrim(coalesce(p_current_user_id, '')));
    v_action text := lower(btrim(coalesce(p_action, '')));
    v_reason text := left(btrim(coalesce(p_reason, '')), 500);
    v_request public.oasis_specific_company_db_requests%rowtype;
    v_contact public.oasis_employment_contacts%rowtype;
    v_claim record;
    v_payload jsonb;
    v_channel text;
begin
    if not public.oasis_sales_actor_is_admin(v_admin) then
        raise exception using
            errcode = '42501',
            message = 'OASIS_SALES_ADMIN_REQUIRED';
    end if;
    if p_request_id is null or v_action not in ('approve', 'reject') then
        return query select false, 'invalid_input',
            '처리할 신청과 작업을 확인해 주세요.',
            p_request_id, null::text, null::uuid;
        return;
    end if;
    if v_action = 'reject' and v_reason = '' then
        return query select false, 'reason_required',
            '반려 사유를 입력해 주세요.',
            p_request_id, null::text, null::uuid;
        return;
    end if;

    perform pg_advisory_xact_lock(
        hashtextextended('oasis-specific-db-request:' || p_request_id::text, 0)
    );
    select r.* into v_request
    from public.oasis_specific_company_db_requests r
    where r.id = p_request_id
    for update;

    if v_request.id is null then
        return query select false, 'not_found',
            '개별 DB 신청을 찾지 못했습니다.',
            p_request_id, null::text, null::uuid;
        return;
    end if;
    if v_request.status <> 'pending' then
        return query select false, 'already_resolved',
            '이미 처리가 끝난 신청입니다.',
            v_request.id, v_request.status, v_request.assignment_id;
        return;
    end if;

    if v_action = 'reject' then
        update public.oasis_specific_company_db_requests r
        set
            status = 'rejected',
            decision_reason = v_reason,
            decided_by_user_id = v_admin,
            decided_at = now(),
            updated_at = now()
        where r.id = v_request.id;
        insert into public.oasis_specific_company_db_request_events (
            request_id, actor_user_id, action, reason
        ) values (v_request.id, v_admin, 'rejected', v_reason);
        return query select true, 'rejected',
            '개별 DB 신청을 반려했습니다.',
            v_request.id, 'rejected', null::uuid;
        return;
    end if;

    select c.* into v_contact
    from public.oasis_employment_contacts c
    where c.contact_key = v_request.source_contact_key
      and c.business_no = v_request.business_no;

    if v_contact.contact_key is null
       or not (
          coalesce(v_contact.has_mobile_phone, false)
          or coalesce(v_contact.has_landline_phone, false)
       ) then
        return query select false, 'contact_unavailable',
            '승인 시점에 유효한 전화번호 DB를 확인하지 못했습니다.',
            v_request.id, v_request.status, null::uuid;
        return;
    end if;

    v_channel := case
        when coalesce(v_contact.has_mobile_phone, false) then 'mobile'
        else 'landline'
    end;
    v_payload := jsonb_build_object(
        'company_uid', v_request.company_uid,
        'business_no', v_request.business_no,
        'company_name', v_contact.company_name,
        'address', v_contact.address,
        'industry_name', v_contact.industry_name,
        'employee_count', coalesce(v_contact.current_employee_count, 0),
        'new_employee_count', greatest(coalesce(v_contact.employee_growth, 0), 0),
        'mobile_phone', v_contact.mobile_phone,
        'landline_phone', v_contact.landline_phone,
        'phone', coalesce(
            nullif(v_contact.mobile_phone, ''),
            nullif(v_contact.landline_phone, ''),
            ''
        ),
        'source', coalesce(nullif(v_contact.source_type, ''), 'specific_db_request'),
        'source_key', coalesce(
            nullif(v_contact.source_record_key, ''),
            v_contact.contact_key
        ),
        'source_data', jsonb_build_object(
            'allocation_channel', v_channel,
            'discovery_type', 'specific_request',
            'specific_db_request_id', v_request.id,
            'contact_key', v_contact.contact_key
        )
    );

    select * into v_claim
    from public.oasis_claim_and_save_company_sales_assignment(
        v_request.requested_user_id,
        v_request.company_uid,
        v_payload,
        left(coalesce(p_session_id, ''), 200)
    );

    if not coalesce(v_claim.success, false) then
        return query select false,
            coalesce(nullif(v_claim.code, ''), 'assignment_failed'),
            coalesce(nullif(v_claim.message, ''), '업체를 배정하지 못했습니다.'),
            v_request.id, v_request.status, null::uuid;
        return;
    end if;

    update public.oasis_specific_company_db_requests r
    set
        status = 'approved',
        decision_reason = v_reason,
        decided_by_user_id = v_admin,
        assignment_id = v_claim.assignment_id,
        prospect_id = v_claim.prospect_id,
        decided_at = now(),
        updated_at = now()
    where r.id = v_request.id;

    insert into public.oasis_specific_company_db_request_events (
        request_id, actor_user_id, action, reason
    ) values (
        v_request.id, v_admin, 'approved',
        coalesce(nullif(v_reason, ''), left(coalesce(p_session_id, ''), 500))
    );

    return query select true, 'approved',
        '개별 DB 신청을 승인하고 신청자에게 배정했습니다.',
        v_request.id, 'approved', v_claim.assignment_id;
end;
$$;

revoke all on function public.oasis_search_company_db_by_business_no(text, text)
    from public, anon, authenticated;
revoke all on function public.oasis_submit_specific_company_db_request(text, text, text)
    from public, anon, authenticated;
revoke all on function public.oasis_list_user_specific_company_db_requests(text, integer)
    from public, anon, authenticated;
revoke all on function public.oasis_list_admin_specific_company_db_requests(text, text[], integer)
    from public, anon, authenticated;
revoke all on function public.oasis_admin_review_specific_company_db_request(text, uuid, text, text, text)
    from public, anon, authenticated;

grant execute on function public.oasis_search_company_db_by_business_no(text, text)
    to service_role;
grant execute on function public.oasis_submit_specific_company_db_request(text, text, text)
    to service_role;
grant execute on function public.oasis_list_user_specific_company_db_requests(text, integer)
    to service_role;
grant execute on function public.oasis_list_admin_specific_company_db_requests(text, text[], integer)
    to service_role;
grant execute on function public.oasis_admin_review_specific_company_db_request(text, uuid, text, text, text)
    to service_role;

comment on function public.oasis_search_company_db_by_business_no(text, text) is
    '정확한 사업자등록번호로 업체를 조회하되 휴대전화 원문은 반환하지 않는다.';
comment on table public.oasis_specific_company_db_requests is
    '사업자등록번호 개별 DB 신청. 전화번호 원문을 저장하지 않는다.';

commit;
